"""Notification delivery: Resend HTML email with stdout fallback."""

from __future__ import annotations

import json
import logging
import os
import textwrap

from trip_a_day.ranker import TripCandidate

logger = logging.getLogger(__name__)


def send_trip_notification(trip: TripCandidate, prefs: dict[str, str]) -> bool:
    """Send the daily trip notification email (or print to stdout if no API key).

    Returns True if delivery succeeded, False otherwise.
    """
    recipients = _parse_recipients(prefs)
    subject = _build_subject(trip)
    html_body = _build_html(trip)
    plain_body = _build_plain(trip)

    api_key = os.environ.get("RESEND_API_KEY", "")
    from_email = os.environ.get("RESEND_FROM_EMAIL", "onboarding@resend.dev")

    if not api_key:
        _print_fallback(subject, plain_body)
        return True

    if not recipients:
        logger.warning("No notification_emails configured; printing to stdout.")
        _print_fallback(subject, plain_body)
        return True

    return _send_via_resend(
        api_key, from_email, recipients, subject, html_body, plain_body
    )


def _parse_recipients(prefs: dict[str, str]) -> list[str]:
    raw = prefs.get("notification_emails", "[]")
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            emails = [e.strip() for e in parsed if e.strip()]
            if emails:
                return emails
    except (json.JSONDecodeError, TypeError):
        pass

    # Fall back to NOTIFICATION_EMAILS env var (also used when DB preference is empty)
    env_emails = os.environ.get("NOTIFICATION_EMAILS", "")
    if env_emails:
        return [e.strip() for e in env_emails.split(",") if e.strip()]

    return []


def _build_subject(trip: TripCandidate) -> str:
    nights = (trip.return_date - trip.departure_date).days
    return (
        f"\u2708\ufe0f Trip of the Day: {trip.city}, {trip.country}"
        f" \u2014 ${trip.cost.total:,.0f} for {nights} nights"
    )


def _build_html(trip: TripCandidate) -> str:
    nights = (trip.return_date - trip.departure_date).days
    distance_str = (
        f"{trip.distance_miles:,.0f} mi" if trip.distance_miles > 0 else "N/A"
    )

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; }}
    h1 {{ color: #1a6496; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th {{ background: #f5f5f5; text-align: left; padding: 8px 12px; border: 1px solid #ddd; }}
    td {{ padding: 8px 12px; border: 1px solid #ddd; }}
    .total {{ font-weight: bold; background: #eaf4fb; }}
    .btn {{ display: inline-block; padding: 10px 20px; background: #1a6496; color: white;
            text-decoration: none; border-radius: 4px; margin: 4px 2px; }}
    .footer {{ font-size: 12px; color: #888; margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px; }}
    .estimate {{ color: #888; font-size: 11px; }}
  </style>
</head>
<body>
  <h1>&#x2708;&#xFE0F; Trip of the Day</h1>
  <h2>{trip.city}, {trip.country}</h2>
  <p>
    <strong>Region:</strong> {trip.region}<br>
    <strong>Departure:</strong> {trip.departure_date.strftime("%B %d, %Y")}<br>
    <strong>Return:</strong> {trip.return_date.strftime("%B %d, %Y")} ({nights} nights)<br>
    <strong>Distance from home:</strong> {distance_str}
  </p>

  <h3>Cost Breakdown</h3>
  <table>
    <tr><th>Component</th><th>Cost (USD)</th></tr>
    <tr><td>&#x2708; Flights (round-trip, all travelers)</td><td>${trip.cost.flights:,.2f}</td></tr>
    <tr><td>&#x1F3E8; Hotel ({nights} nights) *</td><td>${trip.cost.hotel:,.2f}</td></tr>
    <tr><td>&#x1F697; Rental Car *</td><td>${trip.cost.car:,.2f}</td></tr>
    <tr><td>&#x1F374; Food (all travelers) *</td><td>${trip.cost.food:,.2f}</td></tr>
    <tr class="total"><td><strong>Total</strong></td><td><strong>${trip.cost.total:,.2f}</strong></td></tr>
  </table>
  <p class="estimate">* Hotel and food are government per diem rate estimates (GSA / State Dept); car rental is a regional average. Only flight prices are live quotes from Google Flights.</p>

  <h3>Book Now</h3>
  <a class="btn" href="{trip.flight_booking_url}">&#x2708; Book Flights</a>
  <a class="btn" href="{trip.hotel_booking_url}">&#x1F3E8; Book Hotel</a>
  <a class="btn" href="{trip.car_booking_url}">&#x1F697; Find Car Rental</a>

  <div class="footer">
    <p>Generated by <strong>trip-a-day</strong>.</p>
  </div>
</body>
</html>"""


def _build_plain(trip: TripCandidate) -> str:
    nights = (trip.return_date - trip.departure_date).days
    distance_str = (
        f"{trip.distance_miles:,.0f} mi" if trip.distance_miles > 0 else "N/A"
    )
    return textwrap.dedent(f"""\
        ✈️  TRIP OF THE DAY
        ==================
        Destination : {trip.city}, {trip.country} ({trip.region})
        Departure   : {trip.departure_date.strftime("%B %d, %Y")}
        Return      : {trip.return_date.strftime("%B %d, %Y")} ({nights} nights)
        Distance    : {distance_str}

        COST BREAKDOWN
        --------------
        Flights     : ${trip.cost.flights:>10,.2f}  (live quote — Google Flights)
        Hotel    *  : ${trip.cost.hotel:>10,.2f}
        Car      *  : ${trip.cost.car:>10,.2f}
        Food     *  : ${trip.cost.food:>10,.2f}
        ─────────────────────────────────────────
        Total       : ${trip.cost.total:>10,.2f}

        * Hotel and food are government per diem estimates (GSA / State Dept);
          car rental is a regional average. Only flights are live quotes.

        BOOKING LINKS
        -------------
        Flights  : {trip.flight_booking_url}
        Hotel    : {trip.hotel_booking_url}
        Car      : {trip.car_booking_url}
    """)


def _print_fallback(subject: str, plain_body: str) -> None:
    print("\n" + "=" * 60)
    print(f"SUBJECT: {subject}")
    print("=" * 60)
    print(plain_body)
    print("=" * 60 + "\n")
    logger.info("Trip notification printed to stdout (no Resend key configured).")


def _send_via_resend(
    api_key: str,
    from_email: str,
    recipients: list[str],
    subject: str,
    html_body: str,
    plain_body: str,
) -> bool:
    try:
        import resend  # type: ignore[import]

        resend.api_key = api_key
        params: resend.Emails.SendParams = {
            "from": from_email,
            "to": recipients,
            "subject": subject,
            "html": html_body,
            "text": plain_body,
        }
        email = resend.Emails.send(params)
        if email and email.get("id"):
            logger.info("Email sent to %s (id: %s).", recipients, email["id"])
            return True
        else:
            logger.error("Resend returned unexpected response: %s", email)
            return False
    except Exception as exc:
        logger.error("Failed to send email via Resend: %s", exc)
        return False
